### ISSUE TITLE
Restrict full access to "Treasurer" LDAP group

### ISSUE THREAD

**Issue by tylercrumpton** [tylercrumpton/treasure-trove#6]
Eeach user will be able to view their own info, and users in the "Treasurer" LDAP group will be able to view and modify the whole table.

**Comment by hfuller** [comment]
Here is an example group. And by example, I mean the actual group.

# treasurer, groups, makerslocal.org
dn: cn=treasurer,ou=groups,dc=makerslocal,dc=org
description: Treasurers
objectClass: top
objectClass: groupOfUniqueNames
uniqueMember: uid=member1,ou=people,dc=makerslocal,dc=org
uniqueMember: uid=member2,ou=people,dc=makerslocal,dc=org
uniqueMember: uid=member3,ou=people,dc=makerslocal,dc=org
cn: treasurer

You can query for "cn=treasurer" with base dn "ou=groups,dc=makerslocal,dc=org".
